#!/bin/bash
set -e

HOOKS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$HOME/.claude/studio-ops-config.env"

echo "Installing hooks from: $HOOKS_DIR"

if ! command -v uv &> /dev/null; then
    echo "Error: 'uv' is not installed. Please install it first."
    exit 1
fi

DEFAULT_PREFIXES="-Users-$USER-Repos-,-Users-$USER-"

STRIP_PREFIXES=""
FORCE=0
while [[ $# -gt 0 ]]; do
    case $1 in
        --strip-prefixes)
            STRIP_PREFIXES="$2"
            shift 2
            ;;
        --force)
            FORCE=1
            shift
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: $0 [--strip-prefixes 'prefix1,prefix2'] [--force]"
            exit 1
            ;;
    esac
done

mkdir -p "$(dirname "$CONFIG_FILE")"

EXISTING_PREFIXES=""
EXISTING_DEBUG=""
if [ -f "$CONFIG_FILE" ] && [ "$FORCE" != "1" ]; then
    EXISTING_PREFIXES=$(grep '^STUDIO_OPS_STRIP_PREFIXES=' "$CONFIG_FILE" | head -1 | cut -d'=' -f2- | tr -d '"' | tr -d "'")
    EXISTING_DEBUG=$(grep '^STUDIO_OPS_DEBUG=' "$CONFIG_FILE" | head -1 | cut -d'=' -f2)
fi

if [ -n "$STRIP_PREFIXES" ]; then
    echo "Using custom strip prefixes: $STRIP_PREFIXES"
elif [ -n "$EXISTING_PREFIXES" ]; then
    STRIP_PREFIXES="$EXISTING_PREFIXES"
    echo "Preserving existing strip prefixes: $STRIP_PREFIXES"
else
    STRIP_PREFIXES="$DEFAULT_PREFIXES"
    echo "Using default strip prefixes: $STRIP_PREFIXES"
fi

DEBUG_VALUE="${EXISTING_DEBUG:-0}"

if [ -f "$CONFIG_FILE" ]; then
    EXISTING_KEY=$(grep '^STUDIO_OPS_API_KEY=' "$CONFIG_FILE" | head -1 | cut -d'=' -f2 | tr -d '"' | tr -d "'")
fi
if [ -n "$EXISTING_KEY" ]; then
    API_KEY="$EXISTING_KEY"
    echo "Reusing existing API key."
else
    API_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    echo "Generated new API key."
fi

echo "Saving configuration to $CONFIG_FILE..."
if [ -f "$CONFIG_FILE" ]; then
    cp "$CONFIG_FILE" "$CONFIG_FILE.prev"
fi
cat > "$CONFIG_FILE" << EOF
# Studio Ops Hooks Configuration
# Generated by install.sh

# Prefixes to strip from project names in the studio view
STUDIO_OPS_STRIP_PREFIXES="$STRIP_PREFIXES"

# Set to 1 to enable debug logging
STUDIO_OPS_DEBUG=$DEBUG_VALUE

# API key for backend authentication
STUDIO_OPS_API_KEY="$API_KEY"
EOF
if [ -f "$CONFIG_FILE.prev" ]; then
    grep -vE '^(#|STUDIO_OPS_STRIP_PREFIXES=|STUDIO_OPS_DEBUG=|STUDIO_OPS_API_KEY=|$)' "$CONFIG_FILE.prev" >> "$CONFIG_FILE" 2>/dev/null || true
    rm -f "$CONFIG_FILE.prev"
fi

echo "Configuration saved."

echo "Installing studio-ops-hook tool..."
cd "$HOOKS_DIR"
uv tool install --force .

HOOK_CMD="studio-ops-hook"

if ! command -v "$HOOK_CMD" &> /dev/null; then
    echo "Warning: '$HOOK_CMD' not found in PATH. You may need to add ~/.local/bin to your PATH."
    echo "Continuing with installation anyway..."
fi

echo "Configuring Claude settings..."
uv run "$HOOKS_DIR/manage_hooks.py" install --hook-cmd "$HOOK_CMD"

echo ""
echo "Done! Please restart Claude Code to apply changes."
echo ""
echo "Configuration file: $CONFIG_FILE"
echo "This registers hooks GLOBALLY in ~/.claude/settings.json — every Claude"
echo "Code session on this machine will now POST lifecycle events to"
echo "studio-ops's backend (default: http://localhost:8010/api/v1/events),"
echo "in addition to any other hooks (e.g. claude-office's) already installed."
